### ISSUE TITLE
Book source?

### ISSUE THREAD

**Issue by Lagrang3** [MyFirstBitcoin/Bitcoin-Diploma#2]
Please upload the book source code so that others can propose improvements, corrections and translation to other languages.

**Comment by BabaevDaniel** [comment]
There is no "source code" of the book per se (similar to [Mastering Bitcoin](https://github.com/bitcoinbook/bitcoinbook)), but they are working on something like that.
I'm currently working on the Russian translation (with their permission) and integrated it to GitHub.
See in this link: [My First Bitcoin - Russian translation](https://github.com/BabaevDaniel/Bitcoin-Diploma-Russian-Version/tree/main/Translated-text)

**Comment by BabaevDaniel** [comment]
See here: [Translations](https://github.com/MyFirstBitcoin/Translation/tree/main)

**Comment by RealMoneyBTC** [comment]
We will incorporate into the 2024 version of the diploma as well as other content in the future.
