### ISSUE TITLE
Make available as e-book (epub)

### ISSUE THREAD

**Issue by u2ix** [MyFirstBitcoin/Bitcoin-Diploma#5]
It would be beneficial to have a e-book version of the book available in the `epub` format. 
This will give a better reading experience on e-book readers then a simple pdf.

**Comment by MiPrimerBitcoin** [comment]
2024 version in an ebook format as well. 
Appreciate the input

**Comment by RealMoneyBTC** [comment]
2024 release will have ebook format. Thank you

**Comment by u2ix** [comment]
Normalmente we close issues when they are *actually* resolved 🙃 But awesome that it's on the way 🔥
Do you have an idea **when** it will be released?
